# Generated by Django 6.0.4 on 2026-05-19 23:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('IMPRESORA', 'Impresora'), ('LAPTOP', 'Laptop'), ('PANTALLA', 'Pantalla'), ('OTRO', 'Otro')], max_length=30)),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100, unique=True)),
                ('empresa_atencion', models.CharField(blank=True, max_length=120)),
                ('razon_social_cliente', models.CharField(blank=True, max_length=160)),
                ('provincia', models.CharField(blank=True, max_length=80)),
                ('ciudad', models.CharField(blank=True, max_length=80)),
                ('direccion', models.TextField(blank=True)),
                ('area_departamento', models.CharField(blank=True, max_length=120)),
                ('ubicacion_coordenadas', models.URLField(blank=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_equipos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'equipos',
                'ordering': ['tipo', 'marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='TicketSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=40)),
                ('empresa', models.CharField(max_length=140)),
                ('problema', models.TextField()),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_REVISION', 'En revision'), ('RESUELTO', 'Resuelto')], default='NUEVO', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='parque.equipo')),
            ],
            options={
                'verbose_name': 'ticket de soporte',
                'verbose_name_plural': 'tickets de soporte',
                'ordering': ['-creado_en'],
            },
        ),
    ]
